### ISSUE TITLE
How can I get this book

### ISSUE THREAD

**Issue by curryfor30** [metal-by-example/sample-code#10]
Hi! warrenm,I think you are skilled and want to read your book, metal by example, but how should I buy it?

**Comment by Beeblerox** [comment]
You could buy it here: https://gumroad.com/l/metalbyexample (the link is from this page: https://metalbyexample.com/the-book/)

**Comment by warrenm** [comment]
Sorry for the delayed response, and thanks to @Beeblerox for the Gumroad link.
